form:
  domain: www.msftconnecttest.com #登录地址 ip 或域名
  username: "" #账号
  usertype: cmcc #运营商类型，在原网页会被自动附加在账号后，请把 @ 后面的部分填入 user_type，没有则留空（删掉默认的）
  password: "" #密码

meta: #登录参数，这些参数从浏览器抓取使用
  "n": "200"
  type: "1"
  acid: "5"
  enc: srun_bx1

settings:

  basic: #基础设置
    https: false #访问校园网 API 时使用 https 协议
    skip_cert_verify: false #跳过证书有效校验
    timeout: 5 #网络请求超时时间（秒，正整数）
    interfaces: "" #网卡名称正则（注意转义），如：eth0\.[2-3]，不为空时为多网卡模式

  guardian: #守护模式（后台常驻）
    enable: false
    duration: 300 #网络检查周期（秒，正整数）

  log:
    debug_level: false #打印调试日志
    write_file: false #写日志文件
    log_path: ./ #日志文件存放目录路径
    log_name: "" #指定日志文件名

  ddns: # 校园网内网 ip ddns
    enable: false
    domain: www.example.com
    ttl: 600
    provider: "cloudflare" # dns provider 配置见 DDNS 说明
    #zone: "xxxx"
    #token: "xxxx"